deployment:
  tasks:
    - export DEPLOYPATH=/home/srojasw1/public_html/mientreno/app/
    - /usr/bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".cpanel.yml" \
        ./ "$DEPLOYPATH"
